### ISSUE TITLE
preview

### ISSUE THREAD

**Issue by qnsqns** [aglerr/ItemSkins-Files#9]
java.lang.IllegalArgumentException: Plugin cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[commons-lang-2.6.jar:2.6]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:548) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:251) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:247) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at com.ziwoxyt.hyansecosmetics.mclibs.libs.Executor.asyncTimer(Executor.java:30) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.ziwoxyt.itemskins.v1_19_r1.ShowcaseItem.startTeleportTask(ShowcaseItem.java:96) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.ziwoxyt.itemskins.v1_19_r1.ShowcaseItem.preview(ShowcaseItem.java:48) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.ziwoxyt.itemskins.nms.ItemShowcase.showcase(ItemShowcase.java:34) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.ziwoxyt.itemskins.skins.Skin.showcase(Skin.java:32) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.ziwoxyt.itemskins.inventory.SkinInventory.lambda$placeSkins$2(SkinInventory.java:107) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.ziwoxyt.itemskins.mclibs.inventory.SimpleInventory.handleClick(SimpleInventory.java:340) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.ziwoxyt.itemskins.mclibs.inventory.SimpleInventoryManager$InventoryListener.onInventoryClick(SimpleInventoryManager.java:71) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor856.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3403) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:45:51 INFO]: Vegirl issued server command: /itemskins
[00:45:53 ERROR]: Could not pass event InventoryClickEvent to HyanseItemSkins v1.9
java.lang.IllegalArgumentException: Plugin cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[commons-lang-2.6.jar:2.6]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:548) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:251) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:247) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at com.ziwoxyt.hyansecosmetics.mclibs.libs.Executor.asyncTimer(Executor.java:30) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.ziwoxyt.itemskins.v1_19_r1.ShowcaseItem.startTeleportTask(ShowcaseItem.java:96) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.ziwoxyt.itemskins.v1_19_r1.ShowcaseItem.preview(ShowcaseItem.java:48) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.ziwoxyt.itemskins.nms.ItemShowcase.showcase(ItemShowcase.java:34) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.ziwoxyt.itemskins.skins.Skin.showcase(Skin.java:32) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.ziwoxyt.itemskins.inventory.SkinInventory.lambda$placeSkins$2(SkinInventory.java:107) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.ziwoxyt.itemskins.mclibs.inventory.SimpleInventory.handleClick(SimpleInventory.java:340) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.ziwoxyt.itemskins.mclibs.inventory.SimpleInventoryManager$InventoryListener.onInventoryClick(SimpleInventoryManager.java:71) ~[[H物品皮肤]HyanseItemSkins-1.10.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor856.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3403) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by mitchngwen** [comment]
Support is not there, he must live is no 3rd world country or was raised by wolfs. He seems to change the plugin every few months so he can break all our config files, the most recent one was changing the config file folder name?! lol what the heck is that for?
